# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbae72b17b432358279832edec2c18816d3a5818635d6b1ee1290dccae0a0857df4c678df3d366bcf5288b11ff4044f123fc665e75986ac5c61027e5aff46a1

test:
  secret_key_base: 35e722946346716a8cab764c65a7d0156b2b4cf4ca4a0819e351285d3d64ae605bae98eb5ab62f17d7faf8bc6020f805402c354f072e1b271a9d2166d0044bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
